spring.application.name=backend
server.port=8080

# Actuator Endpoints
management.endpoints.web.exposure.include=*
management.endpoints.web.cors.allowed-origins=http://localhost:5173
management.endpoints.web.cors.allowed-methods=GET,PUT,POST,DELETE,OPTIONS


#database
spring.datasource.url=jdbc:mysql://localhost:3306/insurance_claim_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=onkar99
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update