spring.application.name=backend
server.port=8080

# Actuator Endpoints
management.endpoints.web.exposure.include=*
management.endpoints.web.cors.allowed-origins=http://localhost:5173
management.endpoints.web.cors.allowed-methods=GET,PUT,POST,DELETE,OPTIONS
